name: finbert-embeddings
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pytorch=2.2
  - torchvision=0.17
  - torchaudio=2.2
  - numpy=1.26
  - scikit-learn=1.4
  - pandas=2.1
  - pyarrow=15.0
  - matplotlib=3.8
  - pip:
      - transformers==4.38.2
      - accelerate==0.28.0
      - bertopic==0.16.4
